#!/bin/bash

NAME="parrot"
DIR=/home/parrotapp/parrot-docker
USER=parrotapp
GROUP=parrotapp
WORKERS=3
BIND=unix:/home/parrotapp/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=parrot.settings
DJANGO_WSGI_MODULE=parrot.wsgi
LOG_LEVEL=error

cd $DIR
source ../bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-
