# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('package_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('apartment_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packagemanager.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('apartment_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='packagemanager.Apartment')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packagemanager.Resident'),
        ),
    ]
