# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packagemanager', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('description', models.TextField()),
                ('apartment_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packagemanager.Apartment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Category')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packagemanager.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update_type', models.CharField(max_length=100)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='maintenance.MaintenanceRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceupdate',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Staff'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='staff',
            field=models.ManyToManyField(to='maintenance.Staff'),
        ),
        migrations.AddField(
            model_name='comment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.MaintenanceRequest'),
        ),
        migrations.AddField(
            model_name='comment',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packagemanager.Resident'),
        ),
        migrations.AddField(
            model_name='category',
            name='staff',
            field=models.ManyToManyField(to='maintenance.Staff'),
        ),
    ]
