# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Cats',
        ),
    ]
