# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20171121_0733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cats',
            new_name='Category',
        ),
    ]
