# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20171121_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('priority', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='maintenanceitem',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Room'),
        ),
        migrations.AddField(
            model_name='issue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.MaintenanceItem'),
        ),
    ]
