# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packagemanager', '0001_initial'),
        ('maintenance', '0004_auto_20171219_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=25)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('apartment_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packagemanager.Apartment')),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='maintenance.MaintenanceItem'),
        ),
        migrations.AlterField(
            model_name='maintenanceitem',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='maintenance.Room'),
        ),
        migrations.AddField(
            model_name='maintreq',
            name='issue',
            field=models.ManyToManyField(to='maintenance.Issue'),
        ),
        migrations.AddField(
            model_name='maintreq',
            name='item',
            field=models.ManyToManyField(to='maintenance.MaintenanceItem'),
        ),
        migrations.AddField(
            model_name='maintreq',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packagemanager.Resident'),
        ),
        migrations.AddField(
            model_name='maintreq',
            name='room',
            field=models.ManyToManyField(to='maintenance.Room'),
        ),
    ]
