# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20171219_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintreq',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='maintreq',
            name='priority',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
